# --- Android build features ---
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
android.enableR8.fullMode=true
android.r8.runInSeparateProcess=true
android.r8.jvmArgs=-Xmx2g

# --- Compose ---
android.experimental.enableScreenshotTest=true
compose.hot.reload=true
enableComposeCompilerMetrics=false
enableComposeCompilerReports=false

# --- Kotlin ---
kotlin.code.style=official
kotlin.daemon.jvm.options=-Xmx2g -XX\:+UseG1GC -XX\:SoftRefLRUPolicyMSPerMB=1 -XX\:ReservedCodeCacheSize=320m -XX\:+HeapDumpOnOutOfMemoryError
kotlin.daemon.useFallback=false
kotlin.parallel.tasks.in.project=true
kotlin.compiler.execution.strategy=in-process

# --- KSP ---
ksp.incremental=true
ksp.incremental.classpath=true
ksp.incremental.intermodule=true
ksp.project.isolation.enabled=true
ksp.run.in.process=true

# --- Gradle ---
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.isolated-projects=true
org.gradle.jvmargs=-Xmx3g -XX:+UseZGC -XX:+ZGenerational -XX:+UseStringDeduplication -XX:ReservedCodeCacheSize=512m -XX:MaxMetaspaceSize=1g -Xss2m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.welcome=never
